- jol-benchmarks/pom.xml
Update JMH dependency to 1.25.2.
---------
`$ git fetch https://git.openjdk.java.net/jol pull/2/head:pull/2`
`$ git checkout pull/2`
> Update JMH to 1.25.2

- pom.xml
Maven complains otherwise:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.openjdk.jol:jol-core:jar:0.14-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ org.openjdk.jol:jol-core:[unknown-version], /home/shade/temp/jol/jol/jol-core/pom.xml, line 66, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
---------
`$ git fetch https://git.openjdk.java.net/jol pull/6/head:pull/6`
`$ git checkout pull/6`
> Fix maven-surefire-plugin version

- jol-cli/src/main/java/org/openjdk/jol/operations/ObjectShapes.java
SonarCloud instance reports a few easy-to-fix issues in this method.
---------
* [CODETOOLS-7902835](https://bugs.openjdk.java.net/browse/CODETOOLS-7902835): JOL: ObjectShapes.processJAR should close resources properly
`$ git fetch https://git.openjdk.java.net/jol pull/9/head:pull/9`
`$ git checkout pull/9`
> CODETOOLS-7902835: JOL: ObjectShapes.processJAR should close resources properly

- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
- jol-core/src/main/java/org/openjdk/jol/info/GraphLayout.java
SonarCloud instance reports a few places where implicit promotions are not what we want them to be. The most notorious please is in HeapDumpReader::digestObjArray.
---------
* [CODETOOLS-7902836](https://bugs.openjdk.java.net/browse/CODETOOLS-7902836): JOL: Fix incorrect implicit numeric promotions
`$ git fetch https://git.openjdk.java.net/jol pull/10/head:pull/10`
`$ git checkout pull/10`
> CODETOOLS-7902836: JOL: Fix incorrect implicit numeric promotions

- README.md
- jol-core/src/main/java/org/openjdk/jol/info/ClassLayout.java
- jol-core/src/main/java/org/openjdk/jol/vm/HotspotUnsafe.java
- jol-core/src/main/java/org/openjdk/jol/vm/VMOptions.java
- jol-core/src/main/java/org/openjdk/jol/vm/VirtualMachine.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/UniverseData.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/UniverseTask.java
JOL already knows a lot about the target VM. It can also decode the object headers more verbosely.
`JOLSample_14_FatLocking` example output:
```
$ ~/Install/jdk11u-dev/bin/java -cp jol-samples/target/jol-samples.jar org.openjdk.jol.samples.JOLSample_14_FatLocking
**** Fresh object
org.openjdk.jol.samples.JOLSample_14_FatLocking$A object internals:
OFF  SZ   TYPE DESCRIPTION               VALUE
0   8        (object header: mark)     0x0000000000000005 (biasable; age: 0)
8   4        (object header: class)    0x000d5d08
12   4        (object alignment gap)    
Instance size: 16 bytes
Space losses: 0 bytes internal + 4 bytes external = 4 bytes total
**** Before the lock
org.openjdk.jol.samples.JOLSample_14_FatLocking$A object internals:
OFF  SZ   TYPE DESCRIPTION               VALUE
0   8 …
```
> CODETOOLS-7902866: JOL: Rework the instance dump output: formatting, decoding mark/class words, array length

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpStats.java
- jol-cli/src/main/java/org/openjdk/jol/operations/ObjectEstimates.java
- jol-cli/src/main/java/org/openjdk/jol/operations/StringCompress.java
- jol-core/src/main/java/org/openjdk/jol/info/ClassData.java
- jol-core/src/main/java/org/openjdk/jol/info/FieldData.java
- jol-core/src/main/java/org/openjdk/jol/layouters/HotSpotLayouter.java
- jol-core/src/test/java/org/openjdk/jol/layouters/HotspotLayouterRealTest.java
- jol-core/src/test/java/org/openjdk/jol/layouters/LayouterInvariantsTest.java
- jol-samples/src/main/java/org/openjdk/jol/samples/JOLSample_10_DataModels.java
JDK-8237767 added a new layouter. JOL needs to simulate it as well.
---------
* [CODETOOLS-7902869](https://bugs.openjdk.java.net/browse/CODETOOLS-7902869): JOL: Support JDK 15+ field layouter simulation
`$ git fetch https://git.openjdk.java.net/jol pull/14/head:pull/14` \
`$ git checkout pull/14`
`$ git checkout pull/14` \
`$ git pull https://git.openjdk.java.net/jol pull/14/head`
</details>
`$ git pr checkout 14`
`$ git pr show -t 14`
</details>
<a …
> CODETOOLS-7902869: JOL: Support JDK 15+ field layouter simulation

- .github/workflows/pre-integration.yml
Align test JDK lists with the currently released/important JDKs.
---------
* [CODETOOLS-7902932](https://bugs.openjdk.java.net/browse/CODETOOLS-7902932): JOL: Update test JDK lists for GHA
`$ git fetch https://git.openjdk.java.net/jol pull/17/head:pull/17` \
`$ git checkout pull/17`
`$ git checkout pull/17` \
`$ git pull https://git.openjdk.java.net/jol pull/17/head`
</details>
`$ git pr checkout 17`
`$ git pr show -t 17`
</details>
<a …
> CODETOOLS-7902932: JOL: Update test JDK lists for GHA

- jol-core/src/main/java/org/openjdk/jol/info/ClassLayout.java
See the bug report.
---------
* [CODETOOLS-7903075](https://bugs.openjdk.java.net/browse/CODETOOLS-7903075): JOL: Incorrect ClassLayout header/loss calculation for arrays
`$ git fetch https://git.openjdk.java.net/jol pull/20/head:pull/20` \
`$ git checkout pull/20`
`$ git checkout pull/20` \
`$ git pull https://git.openjdk.java.net/jol pull/20/head`
</details>
`$ git pr checkout 20`
`$ git pr show -t 20`
</details>
<a href="https://git.openjdk.java.net/jol/pull/20.diff">https://git.openjdk.ja …
> CODETOOLS-7903075: JOL: Incorrect ClassLayout header/loss calculation for arrays

- .github/workflows/pre-integration.yml
Similar to [JDK-8282225](https://bugs.openjdk.java.net/browse/JDK-8282225), we want the same for JOL.
---------
* [CODETOOLS-7903113](https://bugs.openjdk.java.net/browse/CODETOOLS-7903113): JOL: GHA: Allow one concurrent run per PR only
`$ git fetch https://git.openjdk.java.net/jol pull/21/head:pull/21` \
`$ git checkout pull/21`
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.java.net/jol pull/21/head`
</details>
`$ git pr checkout 21`
`$ git pr show -t 21`
</details>
<a …
> 7903113: JOL: GHA: Allow one concurrent run per PR only 

- jol-core/src/main/java/org/openjdk/jol/info/ClassLayout.java
- jol-core/src/main/java/org/openjdk/jol/vm/Experiments.java
- jol-core/src/main/java/org/openjdk/jol/vm/HotspotUnsafe.java
Project Lilliput aims to reduce the size of the object header. JOL can support that project by detecting the Lilliput VM and printing out object internals more precisely. 
Sample output on JDK 19+:
```
[B object internals:
OFF  SZ   TYPE DESCRIPTION               VALUE
0   8        (object header: mark)     0x0000000000000001 (non-biasable; age: 0)
8   4        (object header: class)    0x00001ea0
12   4        (array length)            5
16   5   byte [B.<elements>             N/A
21   3        (object alignment gap)    
Instance size: 24 bytes
Space losses: 0 bytes internal + 3 bytes external = 3 bytes total
```
Sample output on current Lilliput:
```
[B object internals:
OFF  SZ   TYPE DESCRIPTION               VALUE
0   8        (object header: mark)     0x0000001200000001 (Lilliput)
8 …
```
> CODETOOLS-7903119: JOL: Experimental support for Lilliput

- .github/workflows/pre-integration.yml
- jol-cli/src/main/java/org/openjdk/jol/operations/ClasspathedOperation.java
- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpStats.java
- jol-cli/src/main/java/org/openjdk/jol/operations/ObjectShapes.java
- jol-core/src/main/java/org/openjdk/jol/info/ClassData.java
- jol-core/src/main/java/org/openjdk/jol/info/FieldLayout.java
- jol-core/src/main/java/org/openjdk/jol/info/GraphLayout.java
- jol-core/src/main/java/org/openjdk/jol/layouters/HotSpotLayouter.java
- jol-core/src/main/java/org/openjdk/jol/vm/HotspotUnsafe.java
- jol-core/src/main/java/org/openjdk/jol/vm/VM.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/AttachMain.java
- jol-samples/src/main/java/org/openjdk/jol/samples/JOLSample_14_FatLocking.java
- jol-samples/src/main/java/org/openjdk/jol/samples/JOLSample_27_Colocation.java
- pom.xml
Head JDK 20-ea does not support building with -source/target 7 anymore. JDK 7 is very old and unlikely to be used widely. We can bump the minimal version to JDK 8 to get... ahem... all the new features that release brings!
If you have a strong opinion that we should *not* drop JDK 7 support, please speak up soon.
---------
* [CODETOOLS-7903352](https://bugs.openjdk.org/browse/CODETOOLS-7903352): JOL: Drop support for JDK 7
`$ git fetch https://git.openjdk.org/jol pull/34/head:pull/34` \
`$ git checkout pull/34`
`$ git checkout pull/34` \
`$ git pull https://git.openjdk.org/jol pull/34/head`
</details> …
> CODETOOLS-7903352: JOL: Drop support for JDK 7

- .github/workflows/pre-integration.yml
Time to update our workflows: new JDKs, new OSes, new GH plugins.
---------
* [CODETOOLS-7903363](https://bugs.openjdk.org/browse/CODETOOLS-7903363): JOL: Update pre-integration testing workflows
`$ git fetch https://git.openjdk.org/jol pull/35/head:pull/35` \
`$ git checkout pull/35`
`$ git checkout pull/35` \
`$ git pull https://git.openjdk.org/jol pull/35/head`
</details>
`$ git pr checkout 35`
`$ git pr show -t 35`
</details>
<a …
> CODETOOLS-7903363: JOL: Update pre-integration testing workflows

- jol-core/src/main/java/org/openjdk/jol/vm/HotspotUnsafe.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/Constants.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/ServiceabilityAgentSupport.java
- jol-core/src/main/java/org/openjdk/jol/vm/sa/UniverseTask.java
SA shuffled a few things around in newer JDKs, we need to update JOL support to match it.
---------
* [CODETOOLS-7903364](https://bugs.openjdk.org/browse/CODETOOLS-7903364): JOL: Fix support for modern SA
`$ git fetch https://git.openjdk.org/jol pull/36/head:pull/36` \
`$ git checkout pull/36`
`$ git checkout pull/36` \
`$ git pull https://git.openjdk.org/jol pull/36/head`
</details>
`$ git pr checkout 36`
`$ git pr show -t 36`
</details>
<a …
> CODETOOLS-7903364: JOL: Fix support for modern SA

- jol-core/src/main/java/org/openjdk/jol/vm/HotspotUnsafe.java
We can be a little more clean with VM configuration messages.
---------
* [CODETOOLS-7903366](https://bugs.openjdk.org/browse/CODETOOLS-7903366): JOL: Clean up VM configuration messages
`$ git fetch https://git.openjdk.org/jol pull/37/head:pull/37` \
`$ git checkout pull/37`
`$ git checkout pull/37` \
`$ git pull https://git.openjdk.org/jol pull/37/head`
</details>
`$ git pr checkout 37`
`$ git pr show -t 37`
</details>
<a href="https://git.openjdk.org/jol/pull/37.diff">https://git.openjdk.or …
> 7903366: JOL: Clean up VM configuration messages

- jol-cli/src/main/java/org/openjdk/jol/Main.java
- jol-cli/src/main/java/org/openjdk/jol/operations/EstimatedModels.java
- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpEstimates.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64_Lilliput.java
- jol-core/src/main/java/org/openjdk/jol/layouters/RawLayouter.java
For Lilliput, we want an easy way to estimate the potential footprint improvements. "estimate" should be extended with Lilliput models, and "heapdump-estimate" should be added to read the data from heap dumps.
---------
* [CODETOOLS-7903410](https://bugs.openjdk.org/browse/CODETOOLS-7903410): JOL: Extend "estimate" to heap dumps and Lilliput
`$ git fetch https://git.openjdk.org/jol pull/38/head:pull/38` \
`$ git checkout pull/38`
`$ git checkout pull/38` \
`$ git pull https://git.openjdk.org/jol pull/38/head`
</details>
`$ git pr checkout 38`
`$ git pr show -t 38` …
> 7903410: JOL: Extend "estimate" to heap dumps and Lilliput

- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64_Lilliput.java
A little follow-up for [CODETOOLS-7903411](https://bugs.openjdk.org/browse/CODETOOLS-7903411), Lilliput model should also reply proper compressed refs/klasses status.
---------
* [CODETOOLS-7903412](https://bugs.openjdk.org/browse/CODETOOLS-7903412): JOL: Lilliput model should include info on compressed classes/refs
`$ git fetch https://git.openjdk.org/jol pull/40/head:pull/40` \
`$ git checkout pull/40`
`$ git checkout pull/40` \
`$ git pull https://git.openjdk.org/jol pull/40/head`
</details>
`$ git pr checkout 40`
`$ git pr show -t 40`
</details> …
> 7903412: JOL: Lilliput model should include info on compressed classes/refs

- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
- jol-core/src/main/java/org/openjdk/jol/util/ClassUtils.java
- jol-core/src/test/java/org/openjdk/jol/util/ClassUtilsTest.java
Current "heapdumpstats" prints "Object[]" for all array types. It should print the actual type. Also, the printouts for the class names should be in more human-readable notation, not the JVM binary names.
---------
* [CODETOOLS-7903521](https://bugs.openjdk.org/browse/CODETOOLS-7903521): JOL: heapdumpstats should print array/class names properly (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/45/head:pull/45` \
`$ git checkout pull/45`
`$ git checkout pull/45` \
`$ git pull https://git.openjdk.org/jol.git pull/45/head`
</details>
`$ git pr checkout 45`
View PR using the GUI …
> CODETOOLS-7903521: JOL: heapdumpstats should print array/class names properly

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpEstimates.java
- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpStats.java
- jol-cli/src/main/java/org/openjdk/jol/operations/ObjectShapes.java
- jol-cli/src/main/java/org/openjdk/jol/operations/StringCompress.java
- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
For large heap dumps, it would be convenient to see the read progress.
---------
* [CODETOOLS-7903522](https://bugs.openjdk.org/browse/CODETOOLS-7903522): JOL: Heap dump readers should print progress (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/46/head:pull/46` \
`$ git checkout pull/46`
`$ git checkout pull/46` \
`$ git pull https://git.openjdk.org/jol.git pull/46/head`
</details>
`$ git pr checkout 46`
`$ git pr show -t 46`
</details>
<a …
> CODETOOLS-7903522: JOL: Heap dump readers should print progress

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpStats.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/ModelVM.java
There is a problem in heapdumpstats: it uses the "current VM model" for HotspotLayouter, but sets JVM version as 8. Which means it could actually fail if run on modern JDK.
---------
* [CODETOOLS-7903523](https://bugs.openjdk.org/browse/CODETOOLS-7903523): JOL: heapdumpstats should not assume JDK 8 (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/47/head:pull/47` \
`$ git checkout pull/47`
`$ git checkout pull/47` \
`$ git pull https://git.openjdk.org/jol.git pull/47/head`
</details>
`$ git pr checkout 47`
`$ git pr show -t 47`
</details> …
> 7903523: JOL: heapdumpstats should not assume JDK 8

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpEstimates.java
- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpStats.java
- jol-cli/src/main/java/org/openjdk/jol/operations/ObjectShapes.java
- jol-cli/src/main/java/org/openjdk/jol/operations/StringCompress.java
- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
We need to be able to sort by column, have better descriptions, etc. Additionally, it does not have to read the large arrays for just the stats.
---------
* [CODETOOLS-7903525](https://bugs.openjdk.org/browse/CODETOOLS-7903525): JOL: heapdumpstats usability improvements (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/48/head:pull/48` \
`$ git checkout pull/48`
`$ git checkout pull/48` \
`$ git pull https://git.openjdk.org/jol.git pull/48/head`
</details>
`$ git pr checkout 48`
`$ git pr show -t 48`
</details>
<details><summary>Using diff …
> 7903525: JOL: heapdumpstats usability improvements

- jol-core/pom.xml
- jol-core/src/main/java/org/openjdk/jol/datamodel/DataModel.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model32.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64_Lilliput.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/ModelVM.java
- jol-core/src/main/java/org/openjdk/jol/info/ClassLayout.java
- jol-core/src/main/java/org/openjdk/jol/layouters/HotSpotLayouter.java
- jol-core/src/test/java/org/openjdk/jol/info/ClassLayoutArraysTest.java
- jol-core/src/test/java/org/openjdk/jol/layouters/HotspotLayouterRealTest.java
This is actually not true in current VMs, due to [JDK-8139457](https://bugs.openjdk.org/browse/JDK-8139457). This means HotspotLayouter underestimates the array sizes. This was not caught before, because we did not have good tests for arrays.
---------
* [CODETOOLS-7903532](https://bugs.openjdk.org/browse/CODETOOLS-7903532): JOL: Hotspot layouter assumes array bases are aligned to 4 bytes (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/49/head:pull/49` \
`$ git checkout pull/49`
`$ git checkout pull/49` \
`$ git pull https://git.openjdk.org/jol.git pull/49/head`
</details>
`$ git pr …
> 7903532: JOL: Hotspot layouter assumes array bases are aligned to 4 bytes

- jol-cli/src/main/java/org/openjdk/jol/operations/EstimatedModels.java
- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpEstimates.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/DataModel.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model32.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/Model64_Lilliput.java
- jol-core/src/main/java/org/openjdk/jol/datamodel/ModelVM.java
- jol-core/src/main/java/org/openjdk/jol/layouters/HotSpotLayouter.java
This would help to ballpark the improvements from [JDK-8139457](https://bugs.openjdk.org/browse/JDK-8139457).
---------
* [CODETOOLS-7903535](https://bugs.openjdk.org/browse/CODETOOLS-7903535): JOL: Show array base improvements in heapdump-estimates (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/50/head:pull/50` \
`$ git checkout pull/50`
`$ git checkout pull/50` \
`$ git pull https://git.openjdk.org/jol.git pull/50/head`
</details>
`$ git pr checkout 50`
`$ git pr show -t 50`
</details>
Download …
> 7903535: JOL: Show array base improvements in heapdump-estimates

- jol-core/src/main/java/org/openjdk/jol/info/ClassData.java
- jol-core/src/main/java/org/openjdk/jol/info/FieldData.java
- jol-core/src/main/java/org/openjdk/jol/info/GraphLayout.java
- jol-core/src/main/java/org/openjdk/jol/util/ClassUtils.java
- jol-core/src/test/java/org/openjdk/jol/info/ClassLayoutNamesTest.java
- jol-core/src/test/java/org/openjdk/jol/info/GraphLayoutNamesTest.java
There are a couple of places, where we print out JVM names for classes. Notably, it happens during "footprint". We need to consistently use the human-readable class names everywhere.
---------
* [CODETOOLS-7903569](https://bugs.openjdk.org/browse/CODETOOLS-7903569): JOL: Use human-readable class names consistently (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/51/head:pull/51` \
`$ git checkout pull/51`
`$ git checkout pull/51` \
`$ git pull https://git.openjdk.org/jol.git pull/51/head`
</details>
`$ git pr checkout 51`
`$ git pr show -t 51` …
> CODETOOLS-7903569: JOL: Use human-readable class names consistently

- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
- jol-core/src/main/java/org/openjdk/jol/info/ClassData.java
- jol-core/src/main/java/org/openjdk/jol/util/Multimap.java
Current heap dump parser relies on class records to appear after the superclass records appear. This does not actually hold for hprof: we can emit the subclass records first, and only then emit the superclass records.
Therefore, current heap dump reader is broken when it encounters hierarchical classes. If the superclass was not seen before current class is being parsed, the heap dump reader would silently treat the current class as having _no super klasses_ at all. It would then underestimate the class footprint, because it does not record superclasses.
---------
* [CODETOOLS-7903579](https://bugs.openjdk.org/browse/CODETOOLS-7903579): JOL: Heap dump parser handles superclasses incorrectly (**Bug** - P4)
`$ …
> 7903579: JOL: Heap dump parser handles superclasses incorrectly

- jol-core/src/main/java/org/openjdk/jol/heap/HeapDumpReader.java
- jol-core/src/main/java/org/openjdk/jol/info/FieldData.java
- jol-core/src/main/java/org/openjdk/jol/util/Multimap.java
- jol-core/src/test/java/org/openjdk/jol/info/ClassDataTest.java
[CODETOOLS-7903579](https://bugs.openjdk.org/browse/CODETOOLS-7903579) was not complete for old layouter. There are still problems when superclasses do not have fields.
---------
* [CODETOOLS-7903583](https://bugs.openjdk.org/browse/CODETOOLS-7903583): JOL: Heap dump parser misses superclasses with empty fields (**Enhancement** - P4)
* @stokito (no known openjdk.org user name / role) ⚠️ Review applies to [3f7a88fc](https://git.openjdk.org/jol/pull/54/files/3f7a88fcd95b615c7b7b5787838b55bae8c18cfb)
`$ git fetch https://git.openjdk.org/jol.git pull/54/head:pull/54` \
`$ git checkout pull/54`
`$ git checkout pull/54` \
`$ git pull https://git.openjdk.org/jol.git pull/54/head` …
> 7903583: JOL: Heap dump parser misses superclasses with empty fields

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpDuplicates.java
Clearly visible in reports:
```
DUPS SIZE VALUE
------------------------------------------------------------------------------------------------
5.955 390.219.240 byte[...] { 0, ..., 0 }
1.824 119.566.848 byte[...] { 0, ..., 0 }
1.666.703 40.000.872 byte[3] { }
1.269.514 30.468.336 byte[3] { }
```
---------
* [CODETOOLS-7903643](https://bugs.openjdk.org/browse/CODETOOLS-7903643): JOL: heapdump-duplicates does not print small array contents with non-power-of-2 sizes (**Bug** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/56/head:pull/56` \
`$ git checkout pull/56`
`$ git checkout pull/56` \
`$ git pull https://git.openjdk.org/jol.git pull/56/head`
</details> …
> 7903643: JOL: heapdump-duplicates does not print small array contents with non-power-of-2 sizes

- jol-cli/src/main/java/org/openjdk/jol/operations/HeapDumpEstimates.java
Looking more closely at the report, I don't think we need to see overly large alignments. This only adds visual noise to the report and makes it slower than it should be.
---------
* [CODETOOLS-7903907](https://bugs.openjdk.org/browse/CODETOOLS-7903907): JOL: Further cleanup in heapdump-estimates (**Enhancement** - P4)
`$ git fetch https://git.openjdk.org/jol.git pull/62/head:pull/62` \
`$ git checkout pull/62`
`$ git checkout pull/62` \
`$ git pull https://git.openjdk.org/jol.git pull/62/head`
</details>
`$ git pr checkout 62`
`$ git pr show -t 62`
</details> …
> 7903907: JOL: Further cleanup in heapdump-estimates
